### ISSUE TITLE
R包下载gtex数据与tcga合并分析？

### ISSUE THREAD

**Issue by zhaoliang0302** [ShixiangWang/UCSCXenaTools#1]
1.TCGA上的normal组很少，xena上有单独的TCGA cohort和gtex cohort，这两个单独的可以直接合并分析吗？
2.xena上有名为TCGA TARGET Gtex的数据，看起来是包括了所有sample，文件巨大（gz文件4G多），直接读到R比较困难，我只需要里面单一癌种的数据，什么方法可以实现呢？
3.xena上TCGA数据是标准化过的，后续分析只用limma就可以吗，我看到技能树的教程是deseq、edgR和limma都分析的，但是是把xena的数据加平方-1后分析的（xena上写的是对TCGA原数据log2（count+1）处理的）再差异分析的。那么xena的数据应该怎样分析比较好呢？
![image](https://user-images.githubusercontent.com/42333702/49686065-02dc7280-fb2a-11e8-931b-db845c916f33.png)
谢谢

**Comment by ShixiangWang** [comment]
@zhaoliang0302 

1. 你好，如果两种数据都是标准化的表达数据，尽管单位一致，我也并不建议进行数据的合并，这种处理应该在原始数据阶段就应该进行统一的处理。Toil RNAseq Recompute数据中心恰好提供了TCGA pan, TARGET以及GETx的整合数据（也即你第2点提到的数据集），它进行了重头统一的处理，因此我推荐你下载这个数据。

2. 提取少量样本的方法是有的，但目前就我的认知你还是需要下载整个文件。如果你R基础（或其他编程）够好，你可以采用每次读取文件的少量行进行处理，直至处理完所有文件。针对你这个需求，我接下来会花几天功夫实现这个功能，如果你不着急，可以等我用几天的时间进行更新。

3. 你可以通过绘制箱线图或者密度图看是否数据大致服从正态分布，即可如基因芯片分析一样进行处理。不过，考虑到是RNAseq，我推荐你使用[RSEM expected_count (DESeq2 standardized)](https://xenabrowser.net/datapages/?dataset=TCGA-GTEx-TARGET-gene-exp-counts.deseq2-normalized.log2&host=https%3A%2F%2Ftoil.xenahubs.net&removeHub=https%3A%2F%2Fxena.treehouse.gi.ucsc.edu%3A443)这个数据集，你可以将单位逆向转换为expected_count-deseq2，然后使用Deseq2进行处理。具体处理请看Deseq2文档，我不了解如何处理。

下面是测试过的下载数据的代码，仅供参考。因为文件不多，只是数据大，所以你觉得方面可以直接手动点击下载。


```r
library(UCSCXenaTools)
library(dplyr)


#----------- Find Cohort "TCGA TARGET GTEx"
XenaGenerate(subset = XenaHostNames == "Toil") %>% 
    XenaFilter(filterCohorts = "TCGA TARGET GTEx")
# or
XenaData %>% 
    dplyr::filter(XenaHostNames == "Toil",
                  XenaCohorts == "TCGA TARGET GTEx") %>% 
    XenaGenerate()


data2 = XenaDataUpdate(saveTolocal = FALSE)

#---------- Download


xe = XenaData %>% 
    dplyr::filter(XenaHostNames == "Toil",
                  XenaCohorts == "TCGA TARGET GTEx") %>% 
    XenaGenerate()
 
# Download Clinical Data   
xe %>% 
    XenaFilter(filterDatasets ="TcgaTargetGTEX_phenotype" ) %>% 
    XenaQuery() %>% 
    XenaDownload() -> cli

# XenaDownload()有一个destdir参数，你可以设置下载数据的本地路径

# Load data
data_cli = XenaPrepare(cli)

# Download Gene Expression Data   
xe %>% 
    XenaFilter(filterDatasets = "deseq2-normalized" ) %>% 
    XenaQuery() %>% 
    XenaDownload() -> ge
# Load data - 如果内存撑不住就不要读了
data_ge = XenaPrepare(ge)
```

**Comment by zhaoliang0302** [comment]
> @zhaoliang0302
> 
> 1. 你好，如果两种数据都是标准化的表达数据，尽管单位一致，我也并不建议进行数据的合并，这种处理应该在原始数据阶段就应该进行统一的处理。Toil RNAseq Recompute数据中心恰好提供了TCGA pan, TARGET以及GETx的整合数据（也即你第2点提到的数据集），它进行了重头统一的处理，因此我推荐你下载这个数据。
> 2. 提取少量样本的方法是有的，但目前就我的认知你还是需要下载整个文件。如果你R基础（或其他编程）够好，你可以采用每次读取文件的少量行进行处理，直至处理完所有文件。针对你这个需求，我接下来会花几天功夫实现这个功能，如果你不着急，可以等我用几天的时间进行更新。
> 3. 你可以通过绘制箱线图或者密度图看是否数据大致服从正态分布，即可如基因芯片分析一样进行处理。不过，考虑到是RNAseq，我推荐你使用[RSEM expected_count (DESeq2 standardized)](https://xenabrowser.net/datapages/?dataset=TCGA-GTEx-TARGET-gene-exp-counts.deseq2-normalized.log2&host=https%3A%2F%2Ftoil.xenahubs.net&removeHub=https%3A%2F%2Fxena.treehouse.gi.ucsc.edu%3A443)这个数据集，你可以将单位逆向转换为expected_count-deseq2，然后使用Deseq2进行处理。具体处理请看Deseq2文档，我不了解如何处理。
> 
> 下面是测试过的下载数据的代码，仅供参考。因为文件不多，只是数据大，所以你觉得方便可以直接手动点击下载。
> 
> ```r
> library(UCSCXenaTools)
> library(dplyr)
> 
> 
> #----------- Find Cohort "TCGA TARGET GTEx"
> XenaGenerate(subset = XenaHostNames == "Toil") %>% 
>     XenaFilter(filterCohorts = "TCGA TARGET GTEx")
> # or
> XenaData %>% 
>     dplyr::filter(XenaHostNames == "Toil",
>                   XenaCohorts == "TCGA TARGET GTEx") %>% 
>     XenaGenerate()
> 
> 
> 
> #---------- Download
> 
> 
> xe = XenaData %>% 
>     dplyr::filter(XenaHostNames == "Toil",
>                   XenaCohorts == "TCGA TARGET GTEx") %>% 
>     XenaGenerate()
>  
> # Download Clinical Data   
> xe %>% 
>     XenaFilter(filterDatasets ="TcgaTargetGTEX_phenotype" ) %>% 
>     XenaQuery() %>% 
>     XenaDownload() -> cli
> 
> # XenaDownload()有一个destdir参数，你可以设置下载数据的本地路径
> 
> # Load data
> data_cli = XenaPrepare(cli)
> 
> # Download Gene Expression Data   
> xe %>% 
>     XenaFilter(filterDatasets = "deseq2-normalized" ) %>% 
>     XenaQuery() %>% 
>     XenaDownload() -> ge
> # Load data - 如果内存撑不住就不要读了
> data_ge = XenaPrepare(ge)
> ```

非常感谢你的回答，很详细很感动，我先自己动手试试，太感谢了

**Comment by ShixiangWang** [comment]
完整代码：

```r
xe = XenaData %>% 
    dplyr::filter(XenaHostNames == "Toil",
                  XenaCohorts == "TCGA TARGET GTEx") %>% 
    XenaGenerate()

# Download Clinical Data   
xe %>% 
    XenaFilter(filterDatasets ="TcgaTargetGTEX_phenotype" ) %>% 
    XenaQuery() %>% 
    XenaDownload() -> cli

# XenaDownload()有一个destdir参数，你可以设置下载数据的本地路径

# Load data
data_cli = XenaPrepare(cli)

# Download Gene Expression Data   
xe %>% 
    XenaFilter(filterDatasets = "deseq2-normalized" ) %>% 
    XenaQuery() %>% 
    XenaDownload() -> ge

keep_names = data_cli$sample[data_cli$`_primary_site`=="Brain"]

keep_names = c("sample", keep_names) 

data_ge =  XenaPrepare(gene, use_chunk = TRUE, 
                                      select_cols = colnames(x) %in% keep_names)

```

因为数据很大，表达数据我没有下载测试。

**Comment by zhaoliang0302** [comment]
你好，我测试了代码发现直接用代码下载数据很慢，我在官网上用百度云离线速度很快，但是不知道怎么读进R，是否可以本地挑选想要的sample读取？后面代码没法测试，我不知道是不是先把整个数据读进去再筛选的，如果是这样的话我的电脑无法读进去如此大的数据（transcript expression RNAseq这个集有5G大小，我电脑8G内存），不知道该怎么办了。

**Comment by ShixiangWang** [comment]
可以的。`XenaPrepare()`这个函数支持本地路径，你把

```

data_ge =  XenaPrepare(gene, use_chunk = TRUE, 
                                      select_cols = colnames(x) %in% keep_names)
```

中的`gene`改为本地路径就可以了。

即

```
data_ge =  XenaPrepare("文件路径", use_chunk = TRUE, 
                                      select_cols = colnames(x) %in% keep_names)
```

gz文件下载后不用解压，直接将其路径传入即可。

你先试下。

**Comment by zhaoliang0302** [comment]
十分焦虑，如果可以的话，能否将这两个数据下载下来将brain的数据提取出来呢？万分感谢
![image](https://user-images.githubusercontent.com/42333702/49694954-193c0a00-fbce-11e8-8c8f-14d29c0fe667.png)

**Comment by zhaoliang0302** [comment]
![image](https://user-images.githubusercontent.com/42333702/49695024-9320c300-fbcf-11e8-83ad-6a5fbfe83876.png)
应该是提示内存不足，不知道我那个路径写的对不对

**Comment by ShixiangWang** [comment]
新增一个参数`chunk_size`试试

```
data_ge =  XenaPrepare("文件路径", use_chunk = TRUE,  chunk_size = 10,
                                      select_cols = colnames(x) %in% keep_names)
```

这个调的越小应该需要的内存就越小，你可以试试，如果不行我再看看怎么处理。

**Comment by zhaoliang0302** [comment]
我设为1还是会内存不足

**Comment by ShixiangWang** [comment]
那你只能耐心等待一下了。我需要在我服务器上下载数据并测试。

**Comment by zhaoliang0302** [comment]
好的，可以试一下百度云离线下载速度比较快，谢谢你

**Comment by ShixiangWang** [comment]
安装`chunked`包：

```r
install.packages('chunked')
```


然后把

```r
data_ge =  XenaPrepare("文件路径", use_chunk = TRUE, 
                                      select_cols = colnames(x) %in% keep_names)
```

替换为

```
library(chunked)

data_ge =  read_chunkwise("文件路径",  chunk_size = 10) %>%
                        subset(select = keep_names)

```

更多用法参考：https://github.com/edwindj/chunked

如果这个包都读不进去，那说明剩下的brain 1000多个样本的数据你的电脑内存也撑不起。

**Comment by zhaoliang0302** [comment]
试了一下还是会报错，
![image](https://user-images.githubusercontent.com/42333702/49702565-86828600-fc34-11e8-8736-5f2c89d8628f.png)

**Comment by ShixiangWang** [comment]
@zhaoliang0302 
先把文件解压，然后使用下面两种方法之一：

```r
keep_names = data_cli$sample[data_cli$`_primary_site`=="Brain"] # 这一步自己多看看，或者用其他临床数据选择自己想要的样本
keep_names2 = c("sample", keep_names)
keep_names2 = na.omit(keep_names2)  # 之前的条件判断中结果又NA值，你仔细看下

# 方法1，当use_chunk为TRUE时使用的是read_tsv_chunked函数功能，之前出问题也许可能是因为它首先要解压文件，需要大量内存，所以这里我们先提前解压好文件
data_ge =  XenaPrepare("~/tmp/TcgaTargetGtex_gene_expected_count", use_chunk = TRUE, 
                       select_cols = colnames(x) %in% keep_names2)

# 方法2，使用data.table包
library(data.table)
data_ge2 = fread("~/tmp/TcgaTargetGtex_gene_expected_count", select = keep_names2)
```

第2种方法会快不少。

运行后的结果接近900M，你的电脑应该能读进去

```r
> object.size(data_ge2)
897228640 bytes
> object.size(data_ge)
891753416 bytes
```

如果还有问题，请参考以下方法：

* https://stackoverflow.com/questions/19894194/reading-in-chunks-at-a-time-using-fread-in-package-data-table
* https://community.rstudio.com/t/best-practice-to-handle-out-of-memory-data/734/9

issue我会关闭，如果你还有问题就重新打开。

**Comment by zhaoliang0302** [comment]
读取成功了，非常感谢，但是发现data.table是没有rownames的，我自己把data.table转换成了data.frame，再用xena上的行名加到了dataframe中，如果筛选数据是按列的话是不是行没有改变，我的做法没问题呢？
![image](https://user-images.githubusercontent.com/42333702/49727268-c1270580-fcaa-11e8-9a7b-5c0a37268b8d.png)

**Comment by ShixiangWang** [comment]
设置`data.table=FALSE`读入的就是data frame。

```r
data_ge2 = fread("~/tmp/TcgaTargetGtex_gene_expected_count", select = keep_names2, data.table = FALSE)
```

**Comment by ShixiangWang** [comment]
@zhaoliang0302 
第一列是基因名或转录子名等

下面我列出了第1到4列以及最后一列的信息，由此可以判断第一列为行名，其他列为样本数据，所以加一个"sample"。

```shell
$head TcgaTargetGtex_gene_expected_count | awk 'BEGIN{OFS="\t";}{print $1, $2, $3, $4, $NF}' | column -t

sample              GTEX-S4Q7-0003-SM-3NM8M  TCGA-19-1787-01  TCGA-S9-A7J2-01  GTEX-XV7Q-0426-SM-4BRVN
ENSG00000242268.2   1.5850                   0.0000           4.6439           1.0000
ENSG00000259041.1   0.0000                   0.0000           0.0000           0.0000
ENSG00000270112.3   2.5850                   2.0000           2.8074           1.5850
ENSG00000167578.16  9.9364                   10.3835          9.9144           10.0538
ENSG00000278814.1   0.0000                   0.0000           0.0000           0.0000
ENSG00000078237.5   8.5469                   9.7764           8.7649           8.5078
ENSG00000269416.5   1.0000                   7.1898           5.0875           1.0000
ENSG00000263642.1   0.0000                   0.0000           0.0000           0.0000
ENSG00000146083.11  12.4901                  11.1624          11.9333          11.0821
```

Xena上显示的数据可能是随机提取的，一切以你下载的文件为基准。

**Comment by zhaoliang0302** [comment]
非常感谢，真热心，谢谢你
