### ISSUE TITLE
XenaQuery throws error

### ISSUE THREAD

**Issue by Amhaslam** [ShixiangWang/UCSCXenaTools#37]
![image](https://user-images.githubusercontent.com/30788301/168978357-aaf4da80-3b26-4d75-b1f0-486082454524.png)

**Comment by ShixiangWang** [comment]
@Amhaslam This is typically caused by bad internet. You can retry it after a while. Also could you show all your query code, so I can try reproducing this?

**Comment by Amhaslam** [comment]
thank you for your immediate response,
![image](https://user-images.githubusercontent.com/30788301/168981358-c017d75d-607f-4d51-b447-a19c3875e815.png)

**Comment by ShixiangWang** [comment]
@Amhaslam Hi, this works for me. So you need to check your internet of R to the UCSC data hubs. Or download it with web browser from <https://xenabrowser.net/datapages/?cohort=TCGA%20TARGET%20GTEx&removeHub=https%3A%2F%2Fxena.treehouse.gi.ucsc.edu%3A443>

```r
library(UCSCXenaTools)
data("XenaData")
GEC_toil = XenaGenerate(subset = XenaHostNames == "toilHub") |> 
    XenaFilter(filterDatasets = "TcgaTargetGtex_gene_expected_count")

GEC_toil %>%
    XenaQuery() %>%
    XenaDownload(destdir = "~/../Downloads/")

```

![image](https://user-images.githubusercontent.com/25057508/168982228-92308bce-5ac0-4a3c-82fb-b95926211c35.png)
