### ISSUE TITLE
options(use_hiplot = TRUE) doesn't work

### ISSUE THREAD

**Issue by ayueme** [ShixiangWang/UCSCXenaTools#38]
options(use_hiplot = TRUE) doesn't work and the url "https://xena.hiplot.com.cn/" is not available anymore.

**Comment by ShixiangWang** [comment]
> options(use_hiplot = TRUE) doesn't work and the url "https://xena.hiplot.com.cn/" is not available anymore.

Yeah. You're right. The hiplot mirror doesn't work. @Miachol have you still been maintaining this?

When hiplot is not available, please stick to the default mirror. It's also fast.

**Comment by ayueme** [comment]
> > options(use_hiplot = TRUE) doesn't work and the url "https://xena.hiplot.com.cn/" is not available anymore.
> 
> Yeah. You're right. The hiplot mirror doesn't work. @Miachol have you still been maintaining this?
> 
> When hiplot is not available, please stick to the default mirror. It's also fast.

Thanks, I'll try it.
