### ISSUE TITLE
一个450K芯片的cg位点在多个TCGA肿瘤的pattern

### ISSUE THREAD

**Issue by iamhealthy** [ShixiangWang/UCSCXenaTools#39]
王诗翔，你好：我想看来自450K芯片的具体1个cg位点在多个TCGA肿瘤的beta value模式，有高效的策略吗？像下面这个图(PMID: PMID: 35790732，Fig S1b)。非常感谢。
<img width="649" alt="image" src="https://github.com/ropensci/UCSCXenaTools/assets/15224600/4b90095a-69ac-4f9b-b3d5-033bd5cabe00">

**Comment by ShixiangWang** [comment]
@iamhealthy 单个位点的数据展示目前我们还不支持。

@lishensuo 你帮我确定下哈

**Comment by iamhealthy** [comment]
谢谢。期待有解决方案啊:-)。在在线xena browser网页，倒是可以看/下载单个cg位点在具体一个肿瘤(tumor vs. control)的beta value。但如果想看该位点在多个肿瘤的变化，难道要一个肿瘤一个肿瘤的手动操作？如果是要分别看5位点cg位点，更麻烦。:-)。谢谢~~

**Comment by ShixiangWang** [comment]
这个我们已经实现按单个甲基化水平在泛瘤种的表达了。具体有问题再交流

**Comment by ShixiangWang** [comment]
<img width="2538" alt="image" src="https://github.com/ropensci/UCSCXenaTools/assets/25057508/75140da3-f73c-47db-a998-aa7c2a1b0771">
