### ISSUE TITLE
UCSCXenaTools: Retrieve Gene Expression and Clinical Information from UCSC Xena for Survival Analysis

### ISSUE THREAD

**Issue by gbregni** [ShixiangWang/UCSCXenaTools#40]
Hi, 
I tried to use the markdown published on https://ropensci.org/blog/2019/09/06/ucscxenatools-surv/

This is what happens: 

merged_data = tibble(sampleID = names(KRAS),
                     KRAS_expression = as.numeric(KRAS)) %>%
  left_join(cli, by = "sampleID") %>%
  filter(sample_type == "Primary Tumor") %>%  # Keep only 'Primary Tumor'
  select(sampleID, KRAS_expression, OS.time, OS) %>%
  rename(time = OS.time,
         status = OS)

Error in `auto_copy()`:
! `x` and `y` must share the same src.
ℹ `x` is a <tbl_df/tbl/data.frame> object.
ℹ `y` is a list.
ℹ Set `copy = TRUE` if `y` can be copied to the same source as `x` (may be slow).
Run `rlang::last_trace()` to see where the error occurred.

#I think this is due to the fact that cli is not a 6 x 157 nibble as in your markdown, but rather a list of 2 tibbles ($LUAD_clinicalMatrix # and $LUAD_survival.txt), each containing part of the needed info. Any suggestions? Thanks!

**Comment by ShixiangWang** [comment]
Sorry for the delay. The data source has been changed.

```r
cli = XenaPrepare(cli_query)

cli$LUAD_clinicalMatrix
cli$LUAD_survival.txt
```

You have to merged the two dataframe as a dataframe.
